/* FILENAME: UNITS.H
 * PROGRAMMER: VG4
 * PURPOSE: Globe project declaration module.
 * LAST UPDATE: 07.06.2014
 */

#ifndef __UNITS_H_
#define __UNITS_H_

#include "anim.h"

/* Функция создания объекта анимации */
vg4UNIT * VG4_CowUnitCreate( VOID );

/* Функция создания информационного объекта анимации */
vg4UNIT * VG4_InfoUnitCreate( VOID );

#endif /* __UNITS_H_ */

/* END OF 'UNITS.H' FILE */
